import Head from 'next/head'
import Image from 'next/image'

import FirstHalf from "../components/firsthalf";

import SecondHalf from "../components/secondhalf";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen">
      <div className="w-1/2 h-full relative">
        <Image src="/bg.png" alt="Your Image" layout="fill" objectFit="cover" />
      </div>
      <div className="w-1/2"></div>
    </div>

    </>
  )
}
